# Generated by Django 5.2 on 2026-02-01 08:51

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Profile picture",
                null=True,
                upload_to=authentication.models.avatar_upload_path,
            ),
        ),
    ]
