# Generated by Django 5.2 on 2026-02-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matching", "0006_job_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
